language: java

jdk:
  - oraclejdk8
  - openjdk7

services:
  - redis-server

install: ./mvnw -U install --quiet -DskipTests=true -P bootstrap

script:
  - jdk_switcher use openjdk7
  - ./mvnw clean test -P bootstrap
#  - jdk_switcher use oraclejdk8
#  - ./mvnw -U clean test -P spring5
